% This is an illustration of how ISCCA works.
%
% In this illustration,a 4-channel recording was simulated for 3 subjects. Each recording 
% is a mixture of an early response,a late response, and white noise. 
%
% The late response has the same waveform across subjects and is captured by the first ISCCA
% component. The waveform of the early response slightly varies across subjects and is captured 
% by the second ISCCA component. The noise signal is captured by the 3rd and the 4th ISCCA 
% components. The early response is simulated by a sawtooth signal. Its phase is identical within
% each subject across channels but varies across subjects. Both the early and the late responses 
% have random polarity and amplitude in each channel.

% In this illustration, since the data have only 4 channels, the DSS dimension reduction step is
% omitted and the mCCA is applied to the 4-channel data directly.

clear;clc;close all;
% load simulated neural signals X, which is (time x channel x subject)
% and is generated by simulate_neural_signals.m
load neural_signals
nsubj = 3; % 3 subjects
nch = 4; % 4 channels

% plot the simulated neural signal waveforms
figure(1);
for subj =1:nsubj
    subplot(nsubj,1,subj);hold on
    for channel=1:nch
      % display each channel with an offset
      plot(squeeze(X(channel,:,subj))'-2*channel);
    end
    axis tight;
%     ylim([-1 7]);
    title(['Subject ' num2str(subj)]);
    xlabel('Time');
    ylabel('Power');
    legend('channel 1','channel 2','channel 3','channel 4','Location','eastoutside');
end

% The ISCCA spatial filter is calculated and applyed to the simulated data
isc_count = 4; % retain 4 ISCCA components
W=msetcca0(X,isc_count);  % derive ISCCA matrix
for plotindex=1:isc_count % apply ISCCA to the data
    W0=real(W(:,plotindex,:));
    for subj=1:size(X,3)
        TX(:,subj)=X(:,:,subj)'*W0(:,:,subj);
    end
    % ISC_data contains the ISCCA component (time x subject x component)
    ISC_data(:,:,plotindex) = TX; 
end

% plot ISCCA components
figure(2);
for subj =1:nsubj
    subplot(nsubj,1,subj);hold on
    for channel=1:nch
      plot(zscore(squeeze(ISC_data(:,subj,channel))')+channel-10*channel);
    end
    axis tight;
    title(['subject ' num2str(subj)]);
    xlabel('Time');
    ylabel('Power');
    legend('component 1','component 2','component 3','component 4','Location','eastoutside');
end

